name: animation
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sleek_circular_slider: ^2.0.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  rainbow_color: ^2.0.1
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  flutter_lints: ^2.0.0
 




flutter:

  uses-material-design: true

  
